blog/urls.py
from django.urls import path


from .views import ArticleListView, ArticleDetailView


app_name = 'blog'


urlpatterns = [
    path('', ArticleListView.as_view(), name="article-list"),
    path('article/<slug>', ArticleDetailView.as_view(), name="article-detail"),
]

mysite/urls.py
from django.urls import path

from .views import (
    index,
    contact,
    portfolio,
    portfolio_detail
)


app_name = 'mysite'


urlpatterns = [
    path('', index, name="home"),
    path('contact', contact, name="contact"),
    path('portfolio', portfolio, name="portfolio"),
    path('portfolio/<slug>', portfolio_detail, name="portfolio-detail"),
]

personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote', include('django_summernote.urls')),
    path('', include('mysite.urls')),
    path('blog', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='blog/article/')
    description = models.TextField()
    active = models.BooleanField(default=True)
    tag = models.ManyToManyField(Tag)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article-detail', kwargs={'slug': self.slug})

mysite/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Student(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Portfolio(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    skils = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mysite:portfolio-detail', kwargs={'slug': self.slug})


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=120)
    message = models.TextField()

    def __str__(self):
        return self.email


class SocialLinks(models.Model):
    name = models.CharField(max_length=120)
    link = models.URLField()
    icons = models.ImageField(
        upload_to='images/SocialLinks'
    )
    active = models.BooleanField(default=True)
    order_by = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Tag, Article
# Create your views here.


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/articles.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        tags = Tag.objects.all()
        context['tags'] = tags
        return context



class ArticleDetailView(DetailView):
    template_name = 'blog/article.html'
    model = Article

mysite/views.py
import json
import requests
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .models import Contact, Portfolio
# Create your views here.


def index(request):
    return render(request, 'mysite/index.html', {})


def contact(request):
    if request.method == 'POST':
        r_email = request.POST.get('email')
        r_subject = request.POST.get('subject')
        r_message = request.POST.get('message')

        c = Contact(email=r_email, subject=r_subject, message=r_message)
        c.save()
        return render(request, 'mysite/thank.html', {})
    else:
        return render(request, 'mysite/contact.html', {})


def portfolio(request):
    portfolio = Portfolio.objects.all()
    template_data = {"portfolio_all": portfolio}
    return render(request, 'mysite/portfolio.html', template_data)


def portfolio_detail(request, slug):
    instance = Portfolio.objects.get(slug=slug)
    template_data = {'instance': instance}
    return render(request, 'mysite/portfolio-detail.html', template_data)

blog/templates/blog/article.html
{% extends "base.html" %}

{% block title %}
    {{ object.title }} | {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container" style="margin-top: 100px">
        <h1 center>{{ object.title }}</h1>
        <div class="row">
            <div class="col-sm-8 mx-auto">
                <div class="card">
                    <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.description|safe }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 mx-auto"></div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/articles.html
{% extends "base.html" %}

{% block title %}
    Блог | {{ block.super }}
{% endblock title %}


{% block content %}
    <div class="container" style="margin-top: 100px;">
        <div class="row">
            <div class="col-8 mx-auto">
                {% for object in object_list %}
                    <div class="card" style="margin-bottom: 20px">
                    <img class="card-img-bottom" src="{{ object.image.url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ object.get_absolute_url }}">{{ object.title }}<a></h5>
                            <p class="card-text">{{ object.description|safe|truncatechars:50 }}</p>
                            <p class="card-text"><small class="text-muted">{{ object.update }}</small></p>
                        </div>
                    </div>
                {% empty %}
                    <div class="alert alert-info">
                        Еще нету постов
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
            <div class="col-4 mx-auto">
                    {% for tag in tags %}
                        <a href="#"><span class="badge badge-dark">{{ tag.name }}</span></a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/templates/mysite/contact.html
{% extends "base.html" %}

{% block title %}
    Contact | {{ block.super }}
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 70px;">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            <h1>Залишити повідомлення</h1>
            <form action="{% url 'mysite:contact' %}" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="id-email" class="col-2 col-form-label">Email</label>
                    <div class="col-10">
                        <input id="id-email" class="form-control" type="email" name="email">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id-subject" class="col-2 col-form-label">Тема</label>
                    <div class="col-10">
                        <input id="id-subject" class="form-control" type="text" name="subject">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id-message" class="col-2 col-form-label">Сообщение</label>
                    <div class="col-10">
                        <textarea id="id-message" class="form-control" name="message" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="pull-right">
                    <button type="submit" class="btn btn-primary float-right">Отправить</button>
                </div>
            </form>
        </div>
        <div class="col-sm-4 mx-auto">
            <h1>Контакты</h1>
            <div>
                <ul class="list-group list-group-flush">
                    {% for instance in social_icons %}
                        <li class="list-group-item">
                            <img src="{{ instance.icons.url }}" alt="{{ instance.name }}" width="30">
                            <a href="{{ instance.link }}" target="_blank">{{ instance.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

mysite/templates/mysite/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Home | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="jumbotron paral paralsec">
        <h1 class="display-3">Header</h1>
        <p class="lead">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Architecto ea error maiores tenetur quasi, maxime totam accusamus illum suscipit, 
            minima excepturi voluptatem! Natus voluptatibus deleniti cum quo, 
            similique soluta hic?
        </p>
        <p class="lead">
            <a href="{% url 'blog:article-list' %}" class="btn btn-info btn-md btn-lg" role="button">Блог</a>
        </p>
    </div>
    <section class="container program-languages">
        <div class="row">
            <div class="col-lg-12  text-center">
                <div class="navy-line"></div>
                <h1>Языки программирования</h1>
            </div>
            <div class="col-md-4">
                <p class="image-center">
                    <img src="{% static 'images/index_language_image/machine-learning-python-1.png' %}" width=100 alt="python">
                </p>
                <h2>Python</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
            </div>
            <div class="col-md-4">
                <p class="image-center">
                    <img src="{% static 'images/index_language_image/PHP-Logo-PNG-Clipart.png' %}" width=100 alt="php">
                </p>
                <h2>PHP</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
            </div>
            <div class="col-md-4">
                <p class="image-center">
                    <img src="{% static 'images/index_language_image/javascript.png' %}" width=100 alt="javascript">
                </p>
                <h2>JavaScript</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
            </div>
        </div>
    </section>
    <section class="framework">
        <div class="container">
            <div class="row m-b-lg">
                <div class="col-md-12 text-center">
                    <div class="navy-line"></div>
                    <h1>Framework</h1>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p class="image-center">
                            <img src="{% static 'images/index_framework/django.png' %}" width=100 alt="django">
                        </p>
                        <h2>Django</h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
                    </div>
                    <div class="col-md-4">
                        <p class="image-center">
                            <img src="{% static 'images/index_framework/flask.png' %}" width=100 alt="flask">
                        </p>
                        <h2>Flask</h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
                    </div>
                    <div class="col-md-4">
                        <p class="image-center">
                            <img src="{% static 'images/index_framework/jquery.png' %}" width=100 alt="jQuery">
                        </p>
                        <h2>jQuery</h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque ad velit corrupti consequatur officiis esse libero non a, voluptatibus, similique vitae molestiae saepe inventore quae. Id tempora facilis asperiores sit.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="container cms">
        <div class="row">
            <div class="col-md-12  text-center">
                <div class="navy-line"></div>
                <h1>CMS</h1>
            </div>
            <div class="col-6 offset-3">
                <p class="image-center">
                    <img src="{% static 'images/index_cms/opencart.png' %}" width=100 alt="opencart">
                </p>
                <h2>opencart</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic a reprehenderit odit corrupti earum magnam consequuntur voluptatem esse ullam! Magni nemo quasi commodi quaerat modi minima delectus aut, maiores odit.</p>
            </div>
        </div>
    </section>
{% endblock content %}

mysite/templates/mysite/portfolio-detail.html
{% extends "base.html" %}
{% load static main_tags %}
{% block title %}
    {{ instance.name }} | {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container" style="margin-top: 100px">
        <div class="row">
            <div class="col-8 mx-auto">
                <div class="card mb-3">
                    <img class="card-img-top" src="{% static 'mysite/images/unopinion.png' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ instance.name }}</h5>
                        <p class="card-text">{{ instance.description|safe }}</p>
                        <p class="card-text">
                            {% if instance.skils %}
                                {% for skill in instance.skils|split:", " %}
                                    <span class="badge badge-success">
                                        {{ skill }}
                                    </span>
                                {% endfor %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-4 mx-auto">
            </div>
        </div>
    </div>
{% endblock content %}

mysite/templates/mysite/portfolio.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Portfolio | {{ block.super }}
{% endblock %}

{% block content %}
<div class="container" style="margin-top:100px">
    <div class="card-deck">
        {% for portfolio in portfolio_all %}
            <div class="card">
                <img class="card-img-top" src="{% static 'mysite/images/unopinion.png' %}" alt="Card image cap">
                <div class="card-body">
                    <a href="{{ portfolio.get_absolute_url }}">
                        <h5 class="card-title">{{portfolio.name}}</h5>
                    </a>
                    <p class="card-text">{{ portfolio.description|safe|truncatechars:50 }}</p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

mysite/templates/mysite/thank.html
{% extends "base.html" %}

{% block title %}
    Thanks | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 mx-auto">
            <h1>Thanks you!</h1>
            <p>I`ll get back to you as soon as I can!</p>
            <a href="{% url 'mysite:home' %}" class="btn btn-primary btn-block">Back to home page</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Django Personal Blog{% endblock %}</title>
  </head>
  <body class="landing-page">
    {% include 'layout/navbar.html' %}
    {% block content %}  
    {% endblock content %}
    {% include "layout/footer.html" %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            var menu = $('#nav-scroll');
            $(window).scroll(function() {
                var top = $(this).scrollTop();
                if ( top >= 100 ) {
                    menu.addClass('bgNav');
                } else if ( top <= 200 ) {
                    menu.removeClass('bgNav');
                }
            });
        });
    </script>
    {% comment %} <script>
      $(document).ready(function() {
        $('body').scrollspy({
          target: '.navbar-fixed-top',
          offset: 80
        });

        // Page scrolling
        $('a.page-scroll').bind('click', function(event) {
          var link = $(this);
          $('html, body').stop().animate({
            scrollTop: $(link.attr('href')).offset().top - 50
          }, 500);
          event.preventDefault();
          $('#navbar').collapse('hide');
        })
      })

      var cbpAnimatedHeader = (function() {
        var docElem = document.documentElement,
                header = document.querySelector( '.navbar-default' ),
                didScroll = false,
                changeHeaderOn = 200;
        function init() {
            window.addEventListener( 'scroll', function( event ) {
                if( !didScroll ) {
                    didScroll = true;
                    setTimeout( scrollPage, 250 );
                }
            }, false );
        }
        function scrollPage() {
            var sy = scrollY();
            if ( sy >= changeHeaderOn ) {
                $(header).addClass('navbar-scroll')
            }
            else {
                $(header).removeClass('navbar-scroll')
            }
            didScroll = false;
        }
        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }
        init();

      })();
    </script> {% endcomment %}
  </body>
</html>

templates/layout/footer.html
{% url 'mysite:home' as home %}
<footer class="gray-section footer">
<div class="container">
    <div class="row m-b-lg">
        <div class="col-md-12 text-center">
            <div class="navy-line"></div>
            <h1>Связатся со мной</h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolores officiis ex molestiae, vitae ratione, delectus, dignissimos officia sapiente sequi praesentium ad est modi rem molestias atque! Dolorem nisi odio explicabo.</p>
        </div>
    </div> 
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="{% url 'mysite:contact' %}" class="btn btn-info">Отправить письмо</a>
            <p class="m-t-sm">Или через социальние сети</p>
            <ul class="list-inline social-icon">
                {% for link in social_icons %}
                <li class="list-inline-item">
                    <a href="{{ link.link }}" target="_blank">
                        <img src="{{ link.icons.url }}" width=30 alt="{{ link.name }}">
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center m-t-lg m-b-lg">
            <p>
                <strong>© 2019 Max Cage</strong>
                <br>
                Все права захищены
            </p>
        </div>
    </div>
</div>
</footer>

templates/layout/navbar.html
{% load static %}
{% url 'mysite:home' as home %}
{% url 'mysite:portfolio' as portfolio %}
{% url 'mysite:contact' as contact %}
{% url 'blog:article-list' as article_list %}
<div class="navbar-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" role="navigation"  id="nav-scroll">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ home }}">
                <img src="{% static 'mysite/images/python.png' %}" width="100" alt="brand">
            </a>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav justify-content-end">
                    <li class="nav-item {% if request.path == home %}active{% endif %}">
                        <a class="nav-link" href="{{ home }}">Главная <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% if request.path == portfolio %}active{% endif %}">
                        <a class="nav-link" href="{{ portfolio }}">Портфолио</a>
                    </li>
                    <li class="nav-item {% if request.path == article_list %}active{% endif %}">
                        <a class="nav-link" href="{{ article_list }}">Блог</a>
                    </li>
                    <li class="nav-item {% if request.path == contact %}active{% endif %}">
                        <a class="nav-link" href="{{ contact }}">Контакты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>